books/urls.py
from django.urls import path
from .views import (
    book_list,
    book_detail,
    chapter_detail,
    exercise_detail
)

app_name = 'books'

urlpatterns = [
    path('', book_list, name='book-list'),
    path('<slug>/', book_detail, name='book-detail'),
    path('<book_slug>/<int:chapter_number>',
         chapter_detail,
         name='chapter-detail'),
    path('<book_slug>/<int:chapter_number>/<int:exercise_number>/',
         exercise_detail,
         name='exercise-detail')
]

digital_marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import profile_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('account/profile/', profile_view, name='profile'),
    path('cart/', include('shopping_cart.urls', namespace='cart')),
    path('', include('books.urls', namespace='books'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shopping_cart/urls.py
from django.urls import path
from .views import (
    add_to_cart,
    remove_from_cart,
    order_view,
    checkout
)

app_name = 'shopping_cart'

urlpatterns = [
    path('add-to-cart/<book_slug>/',
         add_to_cart,
         name='add-to-cart'),
    path('remove-from-cart/<book_slug>/',
         remove_from_cart,
         name='remove-from-cart'),
    path('order-summary/', order_view, name='order-summary'),
    path('checkout/', checkout, name='checkout')
]

books/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.shortcuts import redirect, reverse

'''
Author
    Book
        Chapter 1
            Exercise 1
                Solution 1
                Solution 2
                ...
            Exercise 2
            ..
        Chapter 2
'''


class UserLibrary(models.Model):
    books = models.ManyToManyField('Book', blank=True)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def book_list(self):
        return self.books.all()

    class Meta:
        verbose_name = 'User Library'
        verbose_name_plural = 'User Library'


def post_user_signup_receiver(sender, instance, created, *args, **kwargs):
    if created:
        UserLibrary.objects.get_or_create(user=instance)


post_save.connect(post_user_signup_receiver, sender=settings.AUTH_USER_MODEL)


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    slug = models.SlugField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Book(models.Model):
    authors = models.ManyToManyField(Author)
    title = models.CharField(max_length=100)
    publication_date = models.DateTimeField()
    isbn = models.CharField(max_length=16)
    slug = models.SlugField()
    cover = models.ImageField()
    price = models.FloatField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:book-detail", kwargs={
            'slug': self.slug
        })


class Chapter(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    chapter_number = models.IntegerField()
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:chapter-detail", kwargs={
            'book_slug': self.book.slug,
            'chapter_number': self.chapter_number
        })


class Exercise(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    exercise_number = models.IntegerField()
    page_number = models.IntegerField()
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:exercise-detail", kwargs={
            'book_slug': self.chapter.book.slug,
            'chapter_number': self.chapter.chapter_number,
            'exercise_number': self.exercise_number
        })


class Solution(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    solution_number = models.IntegerField()
    image = models.ImageField()

    def __str__(self):
        return f"{self.exercise.title}-{self.pk}"

shopping_cart/models.py
from django.conf import settings
from django.db.models import Sum
from django.db import models
from books.models import Book


class OrderItem(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.book.title


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    ref_code = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username

    def get_total(self):
        return self.items.all().aggregate(order_total=Sum('book__price'))['order_total']


class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    total_amount = models.FloatField()
    date_paid = models.DateTimeField(auto_now_add=True)
    stipe_charge_id = models.CharField(max_length=100)

    def __str__(self):
        return self.stipe_charge_id

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Digital Marketplace</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>
    <div class="container">

    {% include "navbar.html" %}

    {% include 'messages.html' %}

    {% block breadcrumb %}
    {% endblock breadcrumb %}
    
    {% block content %}
    {% endblock content %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/book_detail.html
{% extends "base.html" %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
<ol class="breadcrumb">
<li class="breadcrumb-item" aria-current="page">
    <a href="{% url 'books:book-list' %}">Book List</a>
</li>
<li class="breadcrumb-item active" aria-current="page">
    {{ book.title }}
</li>
</ol>
</nav>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <main class="col-xs-12 col-sm-12 col-md-4">
    {% include "book_snippet.html" with book=book %}
    </main>

    <aside class="col-xs-12 col-sm-12 col-md-8">
    <div class="card">
        <div class="card-header">
            Chapters
        </div>
        <ul class="list-group list-group-flush">
            {% for chapter in book.chapter_set.all %}
            <li class="list-group-item">
            <a href="{{ chapter.get_absolute_url }}">
                {{ chapter.chapter_number }}. {{ chapter.title }}
            </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    
    </aside>
</div>
{% endblock content %}

templates/book_list.html
{% extends "base.html" %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
<ol class="breadcrumb">
<li class="breadcrumb-item active" aria-current="page">Book List</li>
</ol>
</nav>
{% endblock breadcrumb %}

{% block content %}

<h1>This is the book list</h1>
<hr />

<div class="row">
{% for book in queryset %}
<div class="col-4">
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ book.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ book.publication_date }}</h6>
            <p class="card-text">
                {% for author in book.authors.all %}
                    <span>{{ author }}</span> 
                    {% if book.authors.count > 1 %} | {% endif %}
                {% endfor %}
            </p>
            <a href="{{ book.get_absolute_url }}" class="card-link">{{ book }}</a>
        </div>
    </div>
</div>
{% endfor %}
</div>

{% endblock content %}


    

templates/book_snippet.html
<div class="card">
    <div class="card-header">{{ book.title }}</div>
    <img src="{{ book.cover.url }}" class="card-img-top" alt="...">
    <div class="card-body">
        <p class="card-text">Published: {{ book.publication_date }}</p>
    </div>
    {% if book_status != 'owned' %}
        <div class="card-footer">
        {% if book_status == 'in_cart' %}
        <a href="{% url 'cart:remove-from-cart' book.slug %}" class="btn btn-default btn-block">
            Remove from cart
        </a>
        {% else %}
        <a href="{% url 'cart:add-to-cart' book.slug %}" class="btn btn-warning btn-block">
            Add to cart
        </a>
        {% endif %}
        </div>
    {% endif %}
</div>

templates/chapter_detail.html
{% extends "base.html" %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
<ol class="breadcrumb">
<li class="breadcrumb-item" aria-current="page">
    <a href="{% url 'books:book-list' %}">Book List</a>
</li>
<li class="breadcrumb-item" aria-current="page">
   <a href="{{ chapter.book.get_absolute_url }}">
    {{ chapter.book.title }}
    </a>
</li>
<li class="breadcrumb-item active" aria-current="page">
    {{ chapter }}
</li>
</ol>
</nav>
{% endblock breadcrumb %}

{% block content %}

<div class="row">
    <main class="col-md-4">
    {% include "book_snippet.html" with book=chapter.book %}
    </main>

    <aside class="col-md-8">
    <div class="card">
        <div class="card-header">
            Exercises
        </div>
        <ul class="list-group list-group-flush">
            {% for exercise in chapter.exercise_set.all %}
            <li class="list-group-item">
            <a href="{{ exercise.get_absolute_url }}">
                {{ exercise.exercise_number }}. {{ exercise.title }}
            </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    
    </aside>
</div>

{% endblock content %}

templates/checkout.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<link href="{% static 'css/stripe_form.css' %}" rel="stylesheet" />
<h1>Checkout</h1>
<hr />

<p>Order total: ${{ order.get_total }}</p>

  <script src="https://js.stripe.com/v3/"></script>

  <form action="." method="post" id="payment-form">
    {% csrf_token %}
    <div class="stripe-form-row">
      <label for="card-element" class="stripe-label">
        Credit or debit card
      </label>
      <div id="card-element" class="StripeElement StripeElement--empty"><div class="__PrivateStripeElement" style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;"><iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeFrame5" allowpaymentrequest="true" src="https://js.stripe.com/v3/elements-inner-card-a72e9d89e54559d0eb81fe213d92c2da.html#style[base][color]=%2332325d&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;keyMode=test&amp;origin=https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fstripe-js&amp;controllerId=__privateStripeController1" title="Secure payment input frame" style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; height: 19.2px;"></iframe><input class="__PrivateStripeElement-input" aria-hidden="true" aria-label=" " autocomplete="false" maxlength="1" style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;"></div></div>

      <!-- Used to display form errors. -->
      <div id="card-errors" role="alert"></div>
    </div>

    <button>Submit Payment</button>
  </form>

<script src="{% static 'js/stripe_form.js' %}"></script>

{% endblock content %}


    

templates/exercise_detail.html
{% extends "base.html" %}
{% load static %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
<ol class="breadcrumb">
<li class="breadcrumb-item" aria-current="page">
    <a href="{% url 'books:book-list' %}">Book List</a>
</li>
<li class="breadcrumb-item" aria-current="page">
   <a href="{{ exercise.chapter.book.get_absolute_url }}">
    {{ exercise.chapter.book.title }}
    </a>
</li>
<li class="breadcrumb-item" aria-current="page">
    <a href="{{ exercise.chapter.get_absolute_url }}">
    {{ exercise.chapter.title }}
    </a>
</li>
<li class="breadcrumb-item active" aria-current="page">
    {{ exercise.title }}
</li>
</ol>
</nav>

{% endblock breadcrumb %}

{% block content %}

<div class="row">
    <main class="col-md-4">
    {% include "book_snippet.html" with book=exercise.chapter.book %}
    </main>

    <aside class="col-md-8">
    <div class="card">
        <div class="card-header">
            Solutions
        </div>

            {% if book_status == 'owned' %}

            {% for solution in exercise.solution_set.all %}
            <div class="accordion" id="toggle-{{ solution.solution_number }}">
                <div class="card">
                    <div class="card-header" id="heading-{{ solution.solution_number }}">
                    <h2 class="mb-0">
                        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse-{{ solution.solution_number }}" aria-expanded="true" aria-controls="collapse-{{ solution.solution_number }}">
                        Solution {{ solution.solution_number }}
                        </button>
                    </h2>
                    </div>

                    <div id="collapse-{{ solution.solution_number }}" class="collapse" aria-labelledby="heading-{{ solution.solution_number }}" data-parent="#toggle-{{ solution.solution_number }}">
                    <div class="card-body">
                        <img src="{{ solution.image.url }}" class="card-img-top" alt="...">
                    </div>
                    </div>
                </div>
            </div>
            {% endfor %}

            {% else %}
        <div class="text-center">
            <h4>You do not have access to this book. 
            <a href="#">Purchase this book</a> to have access to the solutions
            </h4>
            <img src="{% static 'images/lock.png' %}" />
            {% endif %}
        </div>
    </div>
    
    </aside>
</div>


{% endblock content %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
<a class="navbar-brand" href="{% url 'books:book-list' %}">Marketplace</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarsExample09">
    <ul class="navbar-nav mr-auto">
    {% if request.user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:order-summary' %}">
        {{ request.user|cart_item_count }}
        <i class="fas fa-shopping-cart"></i>
        </a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'account_signup' %}">Signup</a>
    </li>
    {% endif %}
    </ul>
    <a class="text-muted" href="{% url 'profile' %}">Account</a>
</div>
</nav>

templates/old_base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}

    <div>
      <strong>Menu:</strong>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
        <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
        {% else %}
        <li><a href="{% url 'account_login' %}">Sign In</a></li>
        <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}

<h1>Order Summary</h1>
<hr />

<table class="table table-hover table-bordered text-center">
    <tr class="text-center">
        <th>no.</th>
        <th>Title</th>
        <th>Price</th>
    </tr>
    {% for item in order.items.all %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ item.book.title }}
        <span>
        <a href="{% url 'cart:remove-from-cart' item.book.slug %}" class="text-danger">
            <i class="fas fa-trash"></i>
        </a>
        </span>
        </td>
        <td>${{ item.book.price }}</td>
    </tr>
    {% empty %}
    <tr>
    <td colspan="3">
        There are no items in your cart
    </td>
    </tr>
    {% endfor %}
    {% if order.get_total %}
    <tr>
    <td colspan="2">
        <strong class="pull-right">Order total: </strong>
    </td>
    <td colspan="1">
        <strong>${{ order.get_total }}</strong>
    </td>
    </tr>
    {% endif %}
    <tr>
        <td colspan="3">
            <a href="{% url 'books:book-list' %}" class="btn btn-warning pull-left">
            {% if order %}
                Continue shopping
            {% else %}
                Add items to your cart
            {% endif %}
            </a>
        </td>
    </tr>
    {% if order.get_total %}
    <tr>
        <td colspan="3">
            <a href="{% url 'cart:checkout' %}" class="btn btn-primary pull-left">
                Checkout
            </a>
        </td>
    </tr>
    {% endif %}
</table>

{% endblock content %}


    

templates/profile.html
{% extends "base.html" %}

{% block content %}

<h1>Previous orders</h1>
<hr />

<table class="table table-hover table-bordered text-center">
    <tr class="text-center">
        <th>no.</th>
        <th>Reference code</th>
        <th>Amount</th>
        <th>Date</th>
    </tr>
    {% for order in orders %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ order.ref_code }}</td>
        <td>${{ order.get_total }}</td>
        <td>{{ order.payment_set.first.date_paid }}</td>

    </tr>
    {% empty %}
    <tr>
    <td colspan="4">
        You have not purchased anything
    </td>
    </tr>
    {% endfor %}
</table>

{% endblock content %}


    